language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - windows
  - osx

dist: bionic

addons:
  apt:
    packages:
      - libgtk-3-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ninja-build
  homebrew:
    packages:
      - python3
      - ninja

matrix:
  include:
    - os: windows
      before_install:
        - choco install -y python3 ninja
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - pip3 install meson
  - rustup component add rustfmt

env:
  - RUST_BACKTRACE=1

script:
  - cargo test --verbose
  - cargo test --verbose --features static
