language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

dist: xenial
addons:
  apt:
    packages:
      - libgtk-3-dev
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build

install:
  - pip3 install --user meson
  - rustup update nightly
  - rustup run nightly cargo install -f rustfmt-nightly

script:
  - cargo test --verbose
  - cargo test --verbose --features static
