image:
  - Visual Studio 2017

environment:
  global:
    CARGO_INCREMENTAL: "0"
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

matrix:
  allow_failures:
    - CHANNEL: nightly
  fast_finish: true

cache:
  - 'C:\Users\appveyor\.cargo'

install:
  # Checkout submodules
  - git submodule update --init --recursive
  # Download ninja
  - mkdir C:\ninja-build
  - ps: (new-object net.webclient).DownloadFile('https://github.com/mesonbuild/cidata/raw/master/ninja.exe', 'C:\ninja-build\ninja.exe')
  # Set paths to dependencies (based on architecture)
  - set PYTHON_ROOT=C:\Python37-x64
  # Add neccessary paths to PATH variable
  - set PATH=%cd%;C:\ninja-build;%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
  # Add llvm-config.exe to the path
  - set PATH=%PATH%;C:\Libraries\llvm-5.0.0\bin
  # Install meson
  - pip install meson
  # Enable Visual Studio 2017
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  # Install rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  # Print versions
  - rustc --version --verbose
  - cargo --version
  - python --version
  - pip --version
  - meson --version

build_script:
  - cargo build --verbose

test_script:
  - cargo test --verbose
  - cargo test --verbose --features static
